" Name:         Bland
" Description:  Dark colorscheme for vim/ neovim
" Author:       Tom Eloe <tomeloe@gmail.com>
" Maintainer:   Tom Eloe
" Website:      https://teloe.me
" License:      Public domain
" Last Updated: Mon Jan 25 10:11:49 2021

" Generated by Colortemplate v2.1.0

set background=dark

hi clear
let g:colors_name = 'bland'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

hi! link Boolean Constant
hi! link Character Constant
hi! link Conditional Statement
hi! link Debug Special
hi! link Define PreProc
hi! link Delimiter Special
hi! link Exception Statement
hi! link Float Constant
hi! link Function Identifier
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link Macro PreProc
hi! link Number Constant
hi! link Operator Statement
hi! link PopupSelected PmenuSel
hi! link PreCondit PreProc
hi! link QuickFixLine Search
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link StorageClass Type
hi! link String Constant
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#1e232a', '#ff0000', '#407367', '#ebcb8b',
        \ '#0000ff', '#ff00ff', '#96b5b4', '#cccccc', '#d2d2d2', '#ff6400',
        \ '#defe52', '#ffff64', '#0064ff', '#ff64ff', '#64ffff', '#e0e0ed']
  if has('nvim')
    let g:terminal_color_0 = '#1e232a'
    let g:terminal_color_1 = '#ff0000'
    let g:terminal_color_2 = '#407367'
    let g:terminal_color_3 = '#ebcb8b'
    let g:terminal_color_4 = '#0000ff'
    let g:terminal_color_5 = '#ff00ff'
    let g:terminal_color_6 = '#96b5b4'
    let g:terminal_color_7 = '#cccccc'
    let g:terminal_color_8 = '#d2d2d2'
    let g:terminal_color_9 = '#ff6400'
    let g:terminal_color_10 = '#defe52'
    let g:terminal_color_11 = '#ffff64'
    let g:terminal_color_12 = '#0064ff'
    let g:terminal_color_13 = '#ff64ff'
    let g:terminal_color_14 = '#64ffff'
    let g:terminal_color_15 = '#e0e0ed'
  endif
  if get(g:, 'dark_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#cccccc guibg=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#cccccc guibg=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#cccccc guibg=#1e232a gui=NONE cterm=NONE
    hi Terminal guifg=#cccccc guibg=#1e232a gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=fg guibg=#1e232a gui=NONE cterm=NONE
  hi Conceal guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor guifg=#cccccc guibg=#1e232a gui=NONE cterm=NONE
  hi CursorColumn guifg=#cccccc guibg=#1e232a gui=NONE cterm=NONE
  hi CursorLine guifg=#cccccc guibg=#262626 gui=NONE cterm=NONE
  hi CursorLineNr guifg=#cccccc guibg=#1e232a gui=NONE cterm=NONE
  hi DiffAdd guifg=#cccccc guibg=#262626 gui=NONE cterm=NONE
  hi DiffChange guifg=#cccccc guibg=#262626 gui=NONE cterm=NONE
  hi DiffDelete guifg=#cccccc guibg=#262626 gui=NONE cterm=NONE
  hi DiffText guifg=#cccccc guibg=#262626 gui=NONE cterm=NONE
  hi Directory guifg=#cccccc guibg=#1e232a gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#cccccc guibg=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#ff0000 guibg=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#407367 guibg=#262626 gui=NONE cterm=NONE
  hi Folded guifg=#407367 guibg=#262626 gui=NONE cterm=NONE
  hi IncSearch guifg=#262626 guibg=#defe52 gui=standout cterm=NONE
  hi LineNr guifg=#666666 guibg=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=#cccccc guibg=#373b41 gui=NONE cterm=NONE
  hi ModeMsg guifg=#cccccc guibg=#1e232a gui=NONE cterm=NONE
  hi MoreMsg guifg=#cccccc guibg=#1e232a gui=NONE cterm=NONE
  hi NonText guifg=#cccccc guibg=#1e232a gui=NONE cterm=NONE
  hi Pmenu guifg=#cccccc guibg=#262626 gui=NONE cterm=NONE
  hi PmenuSbar guifg=#cccccc guibg=#444444 gui=NONE cterm=NONE
  hi PmenuSel guifg=#cccccc guibg=#373b41 gui=NONE cterm=NONE
  hi PmenuThumb guifg=#cccccc guibg=#1e232a gui=NONE cterm=NONE
  hi Question guifg=#cccccc guibg=#1e232a gui=NONE cterm=NONE
  hi Search guifg=#262626 guibg=#defe52 gui=NONE cterm=NONE
  hi SignColumn guifg=#cccccc guibg=#262626 gui=NONE cterm=NONE
  hi SpecialKey guifg=#cccccc guibg=#1e232a gui=NONE cterm=NONE
  hi SpellBad guifg=#cccccc guibg=#1e232a guisp=#ff0000 gui=NONE cterm=NONE
  hi SpellCap guifg=#cccccc guibg=#1e232a guisp=#0000ff gui=NONE cterm=NONE
  hi SpellLocal guifg=#cccccc guibg=#1e232a guisp=#ff00ff gui=NONE cterm=NONE
  hi SpellRare guifg=#cccccc guibg=#1e232a guisp=#96b5b4 gui=reverse cterm=reverse
  hi StatusLine guifg=#cccccc guibg=#1e232a gui=NONE cterm=NONE
  hi StatusLineNC guifg=#cccccc guibg=#1e232a gui=NONE cterm=NONE
  hi TabLine guifg=#cccccc guibg=#1e232a gui=NONE cterm=NONE
  hi TabLineFill guifg=#cccccc guibg=#1e232a gui=NONE cterm=NONE
  hi TabLineSel guifg=#cccccc guibg=#1e232a gui=NONE cterm=NONE
  hi Title guifg=#cccccc guibg=#1e232a gui=NONE cterm=NONE
  hi VertSplit guifg=#cccccc guibg=#1e232a gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#373b41 gui=NONE cterm=NONE
  hi VisualNOS guifg=#cccccc guibg=#1e232a gui=NONE cterm=NONE
  hi WarningMsg guifg=#cccccc guibg=#1e232a gui=NONE cterm=NONE
  hi WildMenu guifg=#cccccc guibg=#1e232a gui=NONE cterm=NONE
  hi Comment guifg=#407367 guibg=NONE gui=NONE cterm=NONE
  hi Constant guifg=#8a7f71 guibg=NONE gui=NONE cterm=NONE
  hi Error guifg=#ff0000 guibg=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#cccccc guibg=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#cccccc guibg=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#defe52 guibg=NONE gui=NONE cterm=NONE
  hi Special guifg=#875f87 guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#999999 guibg=NONE gui=NONE cterm=NONE
  hi Todo guifg=#defe52 guibg=NONE gui=NONE cterm=NONE
  hi Type guifg=#cccccc guibg=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#cccccc guibg=NONE gui=NONE cterm=NONE
  hi Number guifg=#875f87 guibg=NONE gui=NONE cterm=NONE
  hi CursorIM guifg=NONE guibg=fg gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=#1e232a gui=NONE cterm=NONE
  hi ToolbarButton guifg=#cccccc guibg=#1e232a gui=bold cterm=bold
  hi htmlTag guifg=#666666 guibg=NONE gui=NONE cterm=NONE
  hi htmlEndTag guifg=#666666 guibg=NONE gui=NONE cterm=NONE
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'dark_transp_bg', 0)
    hi Normal ctermfg=252 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=252 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=252 ctermbg=234 cterm=NONE
    if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
      set background=dark
    endif
    hi Terminal ctermfg=252 ctermbg=234 cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=234 cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=252 ctermbg=234 cterm=NONE
  hi CursorColumn ctermfg=252 ctermbg=234 cterm=NONE
  hi CursorLine ctermfg=252 ctermbg=235 cterm=NONE
  hi CursorLineNr ctermfg=252 ctermbg=234 cterm=NONE
  hi DiffAdd ctermfg=252 ctermbg=235 cterm=NONE
  hi DiffChange ctermfg=252 ctermbg=235 cterm=NONE
  hi DiffDelete ctermfg=252 ctermbg=235 cterm=NONE
  hi DiffText ctermfg=252 ctermbg=235 cterm=NONE
  hi Directory ctermfg=252 ctermbg=234 cterm=NONE
  hi EndOfBuffer ctermfg=252 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=196 ctermbg=NONE cterm=NONE
  hi FoldColumn ctermfg=23 ctermbg=235 cterm=NONE
  hi Folded ctermfg=23 ctermbg=235 cterm=NONE
  hi IncSearch ctermfg=235 ctermbg=191 cterm=NONE
  hi LineNr ctermfg=241 ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=252 ctermbg=237 cterm=NONE
  hi ModeMsg ctermfg=252 ctermbg=234 cterm=NONE
  hi MoreMsg ctermfg=252 ctermbg=234 cterm=NONE
  hi NonText ctermfg=252 ctermbg=234 cterm=NONE
  hi Pmenu ctermfg=252 ctermbg=235 cterm=NONE
  hi PmenuSbar ctermfg=252 ctermbg=238 cterm=NONE
  hi PmenuSel ctermfg=252 ctermbg=237 cterm=NONE
  hi PmenuThumb ctermfg=252 ctermbg=234 cterm=NONE
  hi Question ctermfg=252 ctermbg=234 cterm=NONE
  hi Search ctermfg=235 ctermbg=191 cterm=NONE
  hi SignColumn ctermfg=252 ctermbg=235 cterm=NONE
  hi SpecialKey ctermfg=252 ctermbg=234 cterm=NONE
  hi SpellBad ctermfg=252 ctermbg=234 cterm=NONE
  hi SpellCap ctermfg=252 ctermbg=234 cterm=NONE
  hi SpellLocal ctermfg=252 ctermbg=234 cterm=NONE
  hi SpellRare ctermfg=252 ctermbg=234 cterm=reverse
  hi StatusLine ctermfg=252 ctermbg=234 cterm=NONE
  hi StatusLineNC ctermfg=252 ctermbg=234 cterm=NONE
  hi TabLine ctermfg=252 ctermbg=234 cterm=NONE
  hi TabLineFill ctermfg=252 ctermbg=234 cterm=NONE
  hi TabLineSel ctermfg=252 ctermbg=234 cterm=NONE
  hi Title ctermfg=252 ctermbg=234 cterm=NONE
  hi VertSplit ctermfg=252 ctermbg=234 cterm=NONE
  hi Visual ctermfg=NONE ctermbg=237 cterm=NONE
  hi VisualNOS ctermfg=252 ctermbg=234 cterm=NONE
  hi WarningMsg ctermfg=252 ctermbg=234 cterm=NONE
  hi WildMenu ctermfg=252 ctermbg=234 cterm=NONE
  hi Comment ctermfg=23 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=102 ctermbg=NONE cterm=NONE
  hi Error ctermfg=196 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=252 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=252 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=191 ctermbg=NONE cterm=NONE
  hi Special ctermfg=96 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=247 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=191 ctermbg=NONE cterm=NONE
  hi Type ctermfg=252 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=252 ctermbg=NONE cterm=NONE
  hi Number ctermfg=96 ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=234 cterm=NONE
  hi ToolbarButton ctermfg=252 ctermbg=234 cterm=bold
  hi htmlTag ctermfg=241 ctermbg=NONE cterm=NONE
  hi htmlEndTag ctermfg=241 ctermbg=NONE cterm=NONE
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'dark_transp_bg', 0)
    hi Normal ctermfg=White ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=White ctermbg=DarkBlue cterm=NONE
    hi Terminal ctermfg=White ctermbg=DarkBlue cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=DarkBlue cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi CursorColumn ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi CursorLine ctermfg=White ctermbg=Black cterm=NONE
  hi CursorLineNr ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi DiffAdd ctermfg=White ctermbg=Black cterm=NONE
  hi DiffChange ctermfg=White ctermbg=Black cterm=NONE
  hi DiffDelete ctermfg=White ctermbg=Black cterm=NONE
  hi DiffText ctermfg=White ctermbg=Black cterm=NONE
  hi Directory ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi EndOfBuffer ctermfg=White ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi FoldColumn ctermfg=DarkGreen ctermbg=Black cterm=NONE
  hi Folded ctermfg=DarkGreen ctermbg=Black cterm=NONE
  hi IncSearch ctermfg=Black ctermbg=Green cterm=NONE
  hi LineNr ctermfg=Black ctermbg=NONE cterm=NONE
  hi MatchParen ctermfg=White ctermbg=Black cterm=NONE
  hi ModeMsg ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi MoreMsg ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi NonText ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi Pmenu ctermfg=White ctermbg=Black cterm=NONE
  hi PmenuSbar ctermfg=White ctermbg=Black cterm=NONE
  hi PmenuSel ctermfg=White ctermbg=Black cterm=NONE
  hi PmenuThumb ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi Question ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi Search ctermfg=Black ctermbg=Green cterm=NONE
  hi SignColumn ctermfg=White ctermbg=Black cterm=NONE
  hi SpecialKey ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi SpellBad ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi SpellCap ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi SpellLocal ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi SpellRare ctermfg=White ctermbg=DarkBlue cterm=reverse
  hi StatusLine ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi StatusLineNC ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi TabLine ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi TabLineFill ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi TabLineSel ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi Title ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi VertSplit ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi Visual ctermfg=NONE ctermbg=Black cterm=NONE
  hi VisualNOS ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi WarningMsg ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi WildMenu ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi Comment ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Constant ctermfg=Black ctermbg=NONE cterm=NONE
  hi Error ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=White ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=White ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=Green ctermbg=NONE cterm=NONE
  hi Special ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Statement ctermfg=Black ctermbg=NONE cterm=NONE
  hi Todo ctermfg=Green ctermbg=NONE cterm=NONE
  hi Type ctermfg=White ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=White ctermbg=NONE cterm=NONE
  hi Number ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=DarkBlue cterm=NONE
  hi ToolbarButton ctermfg=White ctermbg=DarkBlue cterm=bold
  hi htmlTag ctermfg=Black ctermbg=NONE cterm=NONE
  hi htmlEndTag ctermfg=Black ctermbg=NONE cterm=NONE
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi PopupSelected term=reverse
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: black         #1e232a                   234       DarkBlue
" Color: white         #cccccc                   ~         White
" Color: gray0         #262626                   ~         Black
" Color: gray1         #444444                   ~         Black
" Color: gray2         #666666                   ~         Black
" Color: gray3         #888888                   ~         Black
" Color: gray4         #999999                   ~         Black
" Color: gray5         #373b41                   ~         Black
" Color: brown         #8a7f71                   102       Black
" Color: green         #407367                   ~         DarkGreen
" Color: brightgreen   #DEFE52                   ~         Green
" Color: purple        #875f87                   ~         Magenta
" Color: red           rgb(255,   0,   0)        ~         DarkRed
" Color: yellow        #ebcb8b                   ~         DarkYellow
" Color: blue          rgb(  0,   0, 255)        ~         DarkBlue
" Color: magenta       rgb(255,   0, 255)        ~         DarkMagenta
" Color: cyan          #96b5b4                   ~         DarkCyan
" Color: brightblack   rgb(210, 210, 210)        ~         DarkGrey
" Color: brightred     rgb(255, 100,   0)        ~         LightRed
" Color: brightyellow  rgb(255, 255, 100)        ~         LightYellow
" Color: brightblue    rgb(  0, 100, 255)        ~         LightBlue
" Color: brightmagenta rgb(255, 100, 255)        ~         LightMagenta
" Color: brightcyan    rgb(100, 255, 255)        ~         LightCyan
" Color: brightwhite   #e0e0ed                  231        White
" Term colors: black red green yellow blue magenta cyan white
" Term colors: brightblack brightred brightgreen brightyellow
" Term colors: brightblue brightmagenta brightcyan brightwhite
" vim: et ts=2 sw=2
